version: "3"
services:
    kubemq:
        image: "kubemq/kubemq-community:latest"
        ports:
            - 8080:8080
            - 50000:50000
            - 9090:9090
        environment:
            - KEY=39159d19-7667-48dd-907f-eaf6f32564fd

    redis:
        image: "redis"
        ports:
            - "8088:6379"

    minio:
        image: quay.io/minio/minio
        ports:
            - "3933:9000"
            - "9040:9040"
        environment:
            MINIO_ROOT_USER: "user"
            MINIO_ROOT_PASSWORD: "password"

        command: server /data --console-address ":9040"

    postgres:
        image: "postgis/postgis:13-master"
        ports:
            - "8083:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=docs
        command: ["-c", "timezone=UTC"]

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
        environment:
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports:
            - 9300:9300
            - 9400:9200
